// Discount Date 
export const saleEndDate = new Date("October 25, 2025 23:59:59").getTime();


//data
export const allProducts = [
  {
    id: 1,
    name: "male Shoes",
    price: 200,
    date: "2025-10-26",
    img: "../IMG/1.png",
    gender: "Male",
    countatyOfSela: 2,
    desc: "Comfortable leather sandals designed for daily wear.",
  },
  {
    id: 2,
    name: "Female Shoes",
    price: 200,
    date: "2025-10-21",
    img: "../IMG/2.png",
    gender: "Male",
    countatyOfSela: 1,
    desc: "Comfortable leather sandals designed for daily wear.",
  },
  {
    id: 3,
    name: "Kids shoes",
    price: 200,
    date: "2025-10-21",
    img: "../IMG/3.png",
    gender: "Male",
    countatyOfSela: 3,
    desc: "Comfortable leather sandals designed for daily wear.",
  },
  {
    id: 4,
    name: "4",
    price: 200,
    date: "2025-10-21",
    img: "../IMG/4.png",
    gender: "Male",
    countatyOfSela: 5,
    desc: "Comfortable leather sandals designed for daily wear.",
  },
  {
    id: 5,
    name: "5",
    price: 200,
    date: "2025-10-21",
    img: "../IMG/5.png",
    gender: "Male",
    countatyOfSela: 2,
    desc: "Comfortable leather sandals designed for daily wear.",
  },
  {
    id: 6,
    name: "6",
    price: 200,
    date: "2025-10-21",
    img: "../IMG/6.png",
    gender: "Male",
    countatyOfSela: 2,
    desc: "Comfortable leather sandals designed for daily wear.",
  },
  {
    id: 7,
    name: "7",
    price: 200,
    date: "2025-10-21",
    img: "../IMG/7.png",
    gender: "Male",
    countatyOfSela: 2,
    desc: "Comfortable leather sandals designed for daily wear.",
  },
  {
    id: 8,
    name: "8",
    price: 200,
    date: "2025-10-21",
    img: "../IMG/8.png",
    gender: "Male",
    countatyOfSela: 2,
    desc: "Comfortable leather sandals designed for daily wear.",
  },
  {
    id: 9,
    name: "9",
    price: 300,
    date: "2025-10-21",
    img: "../IMG/9.png",
    gender: "Kids",
    countatyOfSela: 2,
    desc: "Stylish white sneakers with soft inner cushioning.",
  },
  {
    id: 10,
    name: "10",
    price: 180,
    date: "2025-10-22",
    img: "../IMG/10.png",
    gender: "Kids",
    countatyOfSela: 2,
    desc: "Lightweight sports shoes made for all-day comfort.",
  },
  {
    id: 14,
    name: "14",
    price: 350,
    date: "2025-10-24",
    img: "../IMG/14.png",
    gender: "Female",
    countatyOfSela: 2,
    desc: "Premium quality casual shoes crafted for long-lasting durability.",
  },
  {
    id: 15,
    name: "15",
    price: 360,
    date: "2025-10-23",
    img: "../IMG/15.png",
    gender: "Female",
    countatyOfSela: 2,
    desc: "Premium quality casual shoes crafted for long-lasting durability.",
  },
];
